//! Item id -> verified wiki icon filename, for `discord::item_icon_url`'s Discord thumbnails.
//!
//! `content/item_wiki_icons.json` is generated by `site/scripts/osrs-data/fetch-item-wiki-icons.mjs`,
//! which resolves each item's real `File:` page on the wiki (following redirects) rather than
//! guessing a filename from the item's display name - some items' actual file is a differently
//! named redirect (e.g. "Coins.png" -> "Coins 100.png"), and a few have no icon file at all. An
//! item id missing from this map (never queried yet, or genuinely has no wiki icon) falls back to
//! the name-guess in `discord::item_icon_url`.

use std::collections::HashMap;
use std::sync::LazyLock;

static ITEM_WIKI_ICONS: LazyLock<HashMap<i32, String>> = LazyLock::new(|| {
    let raw: HashMap<String, String> = serde_json::from_str(include_str!("content/item_wiki_icons.json"))
        .expect("content/item_wiki_icons.json must parse");
    raw.into_iter()
        .filter_map(|(id, filename)| id.parse::<i32>().ok().map(|id| (id, filename)))
        .collect()
});

pub fn filename(item_id: i32) -> Option<&'static str> {
    ITEM_WIKI_ICONS.get(&item_id).map(String::as_str)
}
